// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BulkDownloadController from "./bulk_download_controller"
application.register("bulk-download", BulkDownloadController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
