version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
    groups:
      rails:
        patterns:
          - "rails"
          - "actioncable"
          - "actionmailbox"
          - "actionmailer"
          - "actionpack"
          - "actiontext"
          - "actionview"
          - "activejob"
          - "activemodel"
          - "activerecord"
          - "activestorage"
          - "activesupport"
          - "railties"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
