server:
  interface: 172.17.0.1
  interface: 127.0.0.1
  access-control: 172.16.0.0/12 allow
  access-control: 127.0.0.0/8 allow
  access-control: ::1/128 allow

  do-not-query-localhost: no

forward-zone:
  name: "."
  forward-addr: 2a00:1098:2c::1       # nat64.net DNS64
  forward-addr: 2a01:4f9:c010:3f02::1  # nat64.net DNS64
  forward-addr: 2a00:1098:2b::1        # nat64.net DNS64

